//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Openccpm.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WbsItems
    {
        public string Id { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public string TaskId { get; set; }
        public string TrackId { get; set; }
        public string StatusId { get; set; }
        public string PriorityId { get; set; }
        public string AssignedId { get; set; }
        public int DoneRate { get; set; }
        public string AuthorId { get; set; }
    
        public virtual TaskItems TaskItems { get; set; }
    }
}
